name: Deploy Web App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Get lowercase repo name
        id: vars
        run: | 
          REPO_NAME=$(echo "${{ github.footballanalysis }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_LOWER=$REPO_NAME" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.amr-salah92 }}/${{ env.REPO_NAME_LOWER }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
