name: Deploy Web App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ lower(github.repository_owner) }}/${{ lower(github.repository_name) }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
