name: Deploy Web App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Generate Docker tag
        id: vars
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="$(echo "${{ github.repository }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')"
          echo "TAG=ghcr.io/${OWNER}/${REPO_NAME}:latest" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify variables
        run: echo "Using tag: ${{ env.TAG }}"
